export const researchPapers = [
  {
    slug: 'ai-readiness',
    title: 'Bangladesh AI Readiness Assessment 2026',
    description: "A comprehensive assessment of Bangladesh's AI readiness across 92 requirements in 15 domains. Score: 47.12/100, Rank 80/188.",
    category: 'Assessment',
    readTime: '20 min read',
    date: '2026-01-20',
    author: 'Emon Hossain',
    excerpt: "A comprehensive assessment of Bangladesh's AI readiness across 92 requirements in 15 domains. Score: 47.12/100, Rank 80/188.",
  },
  {
    slug: 'global-benchmarks',
    title: 'Global AI Benchmarks — 65+ Countries',
    description: 'How Bangladesh compares to 65+ nations on AI readiness. Oxford Insights methodology, cluster analysis, and policy implications.',
    category: 'Global',
    readTime: '15 min read',
    date: '2026-01-15',
    author: 'Emon Hossain',
    excerpt: 'How Bangladesh compares to 65+ nations on AI readiness. Oxford Insights methodology, cluster analysis, and policy implications.',
  },
  {
    slug: 'economic-impact',
    title: 'Economic Impact of AI Adoption in Bangladesh',
    description: 'Six economic multipliers: NBR tax AI, ghost beneficiary elimination, SME productivity, BPO 2.0 exports, land disputes, agricultural yield.',
    category: 'Economics',
    readTime: '18 min read',
    date: '2025-11-20',
    author: 'Emon Hossain',
    excerpt: 'Six economic multipliers: NBR tax AI, ghost beneficiary elimination, SME productivity, BPO 2.0 exports, land disputes, agricultural yield.',
  },
  {
    slug: 'ministry-use-cases',
    title: 'Ministry-by-Ministry AI Use Cases',
    description: 'Practical AI applications across all 20 ministries of Bangladesh — with realistic outcomes, implementation timelines, and ROI estimates.',
    category: 'Policy',
    readTime: '25 min read',
    date: '2025-10-15',
    author: 'Emon Hossain',
    excerpt: 'Practical AI applications across all 20 ministries of Bangladesh — with realistic outcomes, implementation timelines, and ROI estimates.',
  },
  {
    slug: 'policy-regulation',
    title: 'AI Policy & Regulatory Framework',
    description: "Bangladesh's current AI Policy V2.0, Data Protection Ordinance, and the 3 ordinances needed to complete the regulatory stack.",
    category: 'Policy',
    readTime: '16 min read',
    date: '2025-09-10',
    author: 'Emon Hossain',
    excerpt: "Bangladesh's current AI Policy V2.0, Data Protection Ordinance, and the 3 ordinances needed to complete the regulatory stack.",
  },
  {
    slug: 'national-strategy',
    title: 'National AI Strategy — 12 Pillars',
    description: 'A 7-year national AI strategy for Bangladesh built on 12 pillars, with funded mandates, measurable KPIs, and institutional ownership.',
    category: 'Strategy',
    readTime: '22 min read',
    date: '2025-08-20',
    author: 'Emon Hossain',
    excerpt: 'A 7-year national AI strategy for Bangladesh built on 12 pillars, with funded mandates, measurable KPIs, and institutional ownership.',
  },
  {
    slug: 'anti-corruption',
    title: 'Anti-Corruption AI — 4-Layer Framework',
    description: "How AI can systematically detect and prevent corruption in Bangladesh's public procurement, land registry, tax collection, and social protection.",
    category: 'Governance',
    readTime: '19 min read',
    date: '2025-07-15',
    author: 'Emon Hossain',
    excerpt: "How AI can systematically detect and prevent corruption in Bangladesh's public procurement, land registry, tax collection, and social protection.",
  },
  {
    slug: 'bangla-nlp',
    title: 'Bangla AI & Sovereign NLP Stack',
    description: 'Building a sovereign Bangla language AI stack: LLM, OCR, STT, TTS, dialect adaptation. BLP-2025: 69 NLP papers, 8 at ACL 2025.',
    category: 'Technology',
    readTime: '17 min read',
    date: '2025-06-10',
    author: 'Emon Hossain',
    excerpt: 'Building a sovereign Bangla language AI stack: LLM, OCR, STT, TTS, dialect adaptation. BLP-2025: 69 NLP papers, 8 at ACL 2025.',
  },
  {
    slug: 'workforce-education',
    title: 'Workforce & Education — AI Reskilling',
    description: "Four-track reskilling model for Bangladesh's 65M young workforce. KOICA $96M program analysis. New job categories: data annotation, AI auditing.",
    category: 'Education',
    readTime: '14 min read',
    date: '2025-05-20',
    author: 'Emon Hossain',
    excerpt: "Four-track reskilling model for Bangladesh's 65M young workforce. KOICA $96M program analysis. New job categories: data annotation, AI auditing.",
  },
  {
    slug: 'risk-management',
    title: 'Risk Management & Non-Negotiables',
    description: '10 AI failure modes specific to Bangladesh. 17 KPIs for national AI monitoring. Non-negotiable safeguards before any public deployment.',
    category: 'Risk',
    readTime: '16 min read',
    date: '2025-04-15',
    author: 'Emon Hossain',
    excerpt: '10 AI failure modes specific to Bangladesh. 17 KPIs for national AI monitoring. Non-negotiable safeguards before any public deployment.',
  },
]
